server:
  port: 8081

spring:
  main:
    banner-mode: off
    log-startup-info: false
  application:
    name: trip-tools-server
  ai:
    mcp:
      server:
        enabled: true
        name: trip-tools
        version: 1.0.0
        type: SYNC
        protocol: STREAMABLE
        request-timeout: 120s
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s

logging:
  level:
    org.springframework.ai.mcp: WARN
    io.modelcontextprotocol: WARN
  file:
    path: ./logs

trip:
  weather:
    api-key: ${QWEATHER_API_KEY}
    host: ${QWEATHER_HOST:km49vk34x2.re.qweatherapi.com}
    geo-host: ${QWEATHER_GEO_HOST:km49vk34x2.re.qweatherapi.com}
  amap:
    api-key: ${AMAP_API_KEY}
