server:
  port: 8081

spring:
  application:
    name: trip-tools-server
  ai:
    mcp:
      server:
        enabled: true
        name: trip-tools
        version: 1.0.0
        type: SYNC
        protocol: STREAMABLE
        request-timeout: 120s

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG

trip:
  weather:
    api-key: ${QWEATHER_API_KEY:49833bc033c84af6b640f53d548386ba}
    host: ${QWEATHER_HOST:km49vk34x2.re.qweatherapi.com}
    geo-host: ${QWEATHER_GEO_HOST:km49vk34x2.re.qweatherapi.com}
  amap:
    api-key: ${AMAP_API_KEY:8c97dbdfd69aaff4225a66bb92626a72}
